version: '3.5'

services:
    redis:
        image: redis

    backend:
        build: ../../part1/1.11/backend-example-docker/
        environment:
            - REDIS=redis
        ports:
            - 8000:8000
    frontend:
        build: ../../part1/1.10/frontend-example-docker/
        ports:
            - 5000:5000
