version: '3.5'

services:
    redis:
        image: redis

    backend:
        build: ../../part1/1.11/backend-example-docker/
        environment:
            - REDIS=redis
            - DB_USERNAME=foo
            - DB_PASSWORD=bar
            - DB_NAME=foobar
            - DB_HOST=db 
        ports:
            - 8000:8000

    frontend:
        build: ../../part1/1.10/frontend-example-docker/
        ports:
            - 5000:5000
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=foo
            - POSTGRES_PASSWORD=bar
            - POSTGRES_DB=foobar
