version: '3.5'
services:

    proxy:
        privileged: true
        image: jwilder/nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
            - VIRTUAL_HOST=localhost

    redis:
        image: redis
        expose:
            - "80"

    backend:
        build: ../../part1/1.11/backend-example-docker/
        environment:
            - REDIS=redis
            - DB_USERNAME=foo
            - DB_PASSWORD=bar
            - DB_NAME=foobar
            - DB_HOST=db
        ports:
            - 8000:8000
        expose:
            - "80"
        
    frontend:
        build: ../../part1/1.10/frontend-example-docker/
        ports:
            - 5000:5000
        expose:
            - "80"
        environment:
            - API_URL=http://localhost/api/

    db:
        privileged: true
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=foo
            - POSTGRES_PASSWORD=bar
            - POSTGRES_DB=foobar
        volumes:
            - ./db-data:/var/lib/postgresql/data
        expose:
            - "80"
#volumes:
#    db-data:
